// Generated by https://quicktype.io

export interface Clase {
  _id?:             string;
  nombre:          string;
  descripcion?:     string;
  horario:         string;
  duracion:        number;
  instructor?:      string;
  nivelDificultad: string;
}
