
// Generated by https://quicktype.io

export interface Promocion {
  _id?:       string;
  codigo:    number;
  nombre:    string;
  urlImagen: string;
  descuento: number;
  fechaIni:  string | Date;
  fechaFin:  string | Date;
}
