// Generated by https://quicktype.io

export interface Usuario {
  _id?:             string;
  dni:             string;
  nombre:          string;
  apellidos:       string;
  password:        string;
  fechaNacimiento: string | Date;
  telefono:        number;
  correo:          String;
  repetirCorreo:   String;
  direccion:       String;
  estado:          String | boolean;
  fechaIni:        string | Date;
  fechaFin?:        string | Date;
  superUsuario:    boolean;
}

